### ISSUE TITLE
export should export entire usecase / iteration 1 directory, including cforge files and raw files.

### ISSUE THREAD

**Issue by garvk** [genai-apps/aggrag#20]
Extend the export / import feature to include the exporting and importing of entire Iteration instead of a single cforge file. 

The need for this exists because current export only exports the cforge file but not the raw files or the rag indexes that are created. So this requires the user of the 'import' to run everything again from uploading the pdf files to running the indexes again. 

Because the export will enable the export of 'directories', we might have to export as a zip file. 

**We can have multiple options to export that includes export of use case etc or have a single export option**

1. If we go ahead with single option, then we should be able to export the full iteration along with raw files and indexes. (although big indexes might be a problem).
2. Also, and similarly, exporting or importing a **use case** could be allowed. So maybe we want to add the following options in export button:
- Export only configurations (only the cforge file - not recommended)
- Export current iteration (includes raw pdf files and indexes)
- Export current use case (includes all iterations)

In the UI, export options could like how we have an expandable 'Save' button that results into 3 options 'Save', 'Save and Commit', and 'Deploy and host'

In the UI, import could be a single import option, and let the code take the ownership of figuring out what style of import is being done otherwise a new user would find it difficult to export 

@tarun-goyal  @uxRoy19

**Comment by tarun-goyal** [comment]
@Jeet-Jain While testing this, I observed that the importing a zipped folder (of an iteration) is not available at this moment. In that case, until we have the full functionality available, let's keep the "exporting an iteration" option disabled. We will have a two value dropdown for Export CTA - (i) Export workflow config, (ii) Export iteration

Let's discuss this today before you make any changes.
