### ISSUE TITLE
Introduction of "hints" for the user when they are new/stuck

### ISSUE THREAD

**Issue by tarun-goyal** [genai-apps/aggrag#26]
- [x] The first time user opens the app, drop a hint to create a new use case or iteration via **Use Cases+** CTA.
- [x] For a new iteration (blank state), drop a hint to start adding nodes via **Add Node+** CTA
- [x] After adding **Text Fields Node** / **File Fields Node** to the screen, drop a hint to connect them to a **Prompt Node**. Also, to declare variables using brackets in the Prompt Node.
- [x] After uploading a file in **Upload File Node** AND adding at least one RAG, drop a hint to **create indexes** before hitting **Play**.
- [x] After **Play** run is finished, drop a hint to add an **Evaluator** or **Visualizer** node to evaluate/inspect/visualize the responses further.
- [x] If a user adds at least one model for querying, drop a hint to add the associated API key in AggRag settings (to avoid the error later).

@uxRoy19 Please review these points.

**Comment by tarun-goyal** [comment]
@uxRoy19 I still dont see any changes for Hint 6. It should appear as soon as someone adds a model in "Model to query" (like for example you have shown a model (GPT3.5) added to Models to query in the 4th screenshot above.

**Comment by uxRoy19** [comment]
In static screenshot it is not possible to show it exactly, let me see if I can create a videoclip of the same.

**Comment by tarun-goyal** [comment]
@uxRoy19 Hey thats fine. No need to spend time on that. Just ensure that whoever works on this, is clear on when should this hint appear.

**Comment by uxRoy19** [comment]
Sure. Let me know whoever is working on the hints, I will work with them on the same.

**Comment by uxRoy19** [comment]
@tarun-goyal for hint2, there is a lit bit of complication.

Let's say instead of a Text-filed node or file-field node, user adds a prompt node, or evaluation node for example, then there has to be some kind of hint to address those cases right? or else that maybe a blocker for the user?

Let me know your thoughts

**Comment by garvk** [comment]
@tarun-goyal  @uxRoy19 great work on the designs and thought behind adding hints. Immediately the UI appears more intuitive should someone pay attention to the hints. 

I want to suggest that we need two hints below:
1. When some one adds prompt node, we need to advise them to add llm or RAG as per their use case. 
2. Also, if they add RAG then we need to tell them the process to create index viz. adding a file node + connecting it with {rag_knowledge_base} variable

**Comment by garvk** [comment]
@santhosh-kumar12532 When I add a javascript processor node, the hint says I can use python code. Please look at this behaviour when you get a chance. 

![Image](https://github.com/user-attachments/assets/596b0b0f-7833-4ec8-ab8d-476cb64b2536)

**Comment by tarun-goyal** [comment]
> [@tarun-goyal](https://github.com/tarun-goyal) [@uxRoy19](https://github.com/uxRoy19) great work on the designs and thought behind adding hints. Immediately the UI appears more intuitive should someone pay attention to the hints.
> 
> I want to suggest that we need two hints below:
> 
> 1. When some one adds prompt node, we need to advise them to add llm or RAG as per their use case.
> 2. Also, if they add RAG then we need to tell them the process to create index viz. adding a file node + connecting it with {rag_knowledge_base} variable

@garvk For the second point above, I believe we already have a hint covering all these points. I haven't got a chance to comprehensively test the hints, but I'll be doing that very soon.
