### ISSUE TITLE
Add new AI services or llm models for RAGs in ragstore, including llama 

### ISSUE THREAD

**Issue by garvk** [genai-apps/aggrag#30]
Sub-Tasks-

1) Eliminate deploymnet names i:e, vadi ones in existing codebase, now this should be coming from  .env file while running Aggrag codebase.

2) Add Together AI service, in ai_service with  "mixtral_8x7b_instruct"  model in alignment with existing codebase  and then move towards adding Replicate ai_service.

3) Documentation page on 'how to add a new model for RAGs in the ragstore' and 'how to add new AI service for RAGs'

**Comment by himanshu-mishra3** [comment]
[Adding_an_AI_Service_and_models_to_AggRag - Copy.docx](https://github.com/user-attachments/files/16757740/Adding_an_AI_Service_and_models_to_AggRag.-.Copy.docx)

**Comment by himanshu-mishra3** [comment]
Sub Task 3. Documentation on Adding AI Services and LLM models 
Attached Documentation.

[Adding_an_AI_Service_and_models_to_AggRag.pdf](https://github.com/user-attachments/files/16757771/Adding_an_AI_Service_and_models_to_AggRag.pdf)
