### ISSUE TITLE
Generate examples and insights to be used in our upcoming research piece 

### ISSUE THREAD

**Issue by garvk** [genai-apps/aggrag#42]
Likely actions to be performed:

1. Identify characteristics of different RAGs in Ragstore currently, viz. Base, Subqa, Raptor etc
2. Generate examples and prove the value of aggrag 
3. Use some examples to lay the foundation for the research piece 

Actionable items:

- [ ] Come up with examples (let's have an initial fixed number of examples):
  - [ ] Evaluate example queries across all RAGs.
  - [ ] Filter examples which best portrays the concept of AggRAG.
  - [ ] Fine tune the queries and finalise the research piece examples.
- [ ] Come up with the flow, content, sub-sections.
- [ ] Create a first draft showcasing how RAG ensembles work.

**Comment by Munir-fractal** [comment]
Examples:

[rag_analysis-examples.pdf](https://github.com/user-attachments/files/16757599/rag_analysis-examples.pdf)



[AI_domain_eg.pdf](https://github.com/user-attachments/files/16757603/AI_domain_eg.pdf)
