### ISSUE TITLE
Implement RAGAS and Deepeval libraries into Aggrag as separate "Evaluator" nodes

### ISSUE THREAD

**Issue by kangkan-fractal** [genai-apps/aggrag#55]
- Deepeval: https://github.com/confident-ai/deepeval
- RAGAS: https://docs.ragas.io/en/stable/
- Figure out the best way to run this: a) in front-end using Pyodide or b) run it as back-end Flask API code

**Comment by ramyaFractal** [comment]
1. LlamaIndex has dependencies that may not be fully supported in Pyodide.

2. LlamaIndex and related AI models might be too resource-intensive to run efficiently in a browser-based environment like Pyodide.

https://github.com/pyodide/pyodide-recipes/issues/251 - This is a ticket to pyodide library to add llama-index support.
